### ISSUE TITLE
Window size paramter is locked 

### ISSUE THREAD

**Issue by Diego-Camacho** [mervesa/HiCDCPlus#10]
Greetings,

I've been trying to tune my tad calling changig the window size parameter that is stated inside the function gi_list_topdom.

Nontheless, It seems to be locked by the source code at a size of 5. 
Here is the body of the function:

function (gi_list, chrs = NULL, file_out = FALSE, fpath = NULL,
    window.size = 5, verbose = FALSE)
{
    if (is.null(chrs)) {
        chrs <- names(gi_list)
    }
    gi_list <- gi_list[chrs]
    out <- list()
    for (chrom in chrs) {
        m <- InteractionSet::inflate(gi_list[[chrom]], rows = gi_list[[chrom]]@regions,
            columns = gi_list[[chrom]]@regions, fill = mcols(gi_list[[chrom]])$counts)@matrix
        m[is.na(m)] <- 0
        rownames(m) <- NULL
        chr <- unique(GenomicRanges::seqnames(gi_list[[chrom]]@regions))
        sub_mat <- cbind.data.frame(GenomicRanges::seqnames(gi_list[[chrom]]@regions),
            GenomicRanges::start(gi_list[[chrom]]@regions), GenomicRanges::end(gi_list[[chrom]]@regions),
            m)
        colnames(sub_mat) = NULL
        tmpfile <- paste0(base::tempfile(), ".txt")
        data.table::fwrite(sub_mat, tmpfile, sep = "\t", col.names = FALSE,
            row.names = FALSE, quote = FALSE)
        outfile <- NULL
        if (file_out)
            outfile <- path.expand(paste0(fpath, "_", chr))
        out[[chrom]] <- .TopDom(matrix.file = tmpfile, window.size = 5,
            outFile = outfile, verbose = verbose)
        system2("rm", args = path.expand(tmpfile))
    }
    return(out)
}

Even the window.size paramter is stated the body of the function does not use it,.

I was wondering if this was coded un purpose and if there's any chance to free the paramter for further tunning, 

Thanks on advance,

Diego

**Comment by mervesa** [comment]
You're correct, this was a typo in the code. I'll pass the `window.size` parameter to the call to the private function and keep you posted once I merge the commit.

**Comment by mervesa** [comment]
Hi, I've just pushed the changes to here and to Bioconductor's current release. The most timely way to use the changes would be to reinstall the package using `devtools` : `library(devtools);
install_github("mervesa/HiCDCPlus")`
