### ISSUE TITLE
There is no "file_out=TRUE" in hic2icenorm_gi_list function

### ISSUE THREAD

**Issue by TingtingSsl2** [mervesa/HiCDCPlus#12]
Dear HiCDCPlus developers,

I'm using hic2icenorm_gi_list before finding TADs. The instruction (https://github.com/mervesa/HiCDCPlus) says that there is `file_out=TRUE` option to output normalized data. "You can also output a ICE normalized .hic file from hic2icenorm_gi_list function if you set file_out=TRUE with the name of gsub(".hic","_icenorm.hic",hic_path)." 

However, the help page found only `hic_output` and this `hic_output` can only direct output to the input file folder, not to customized location.  I'm wondering if you can help with this confusion. 

Bests,

Tingting

**Comment by mervesa** [comment]
Hello @TingtingSsl2 , you are correct and the README is misleading in that it gives an appearance of custom file outputs while the only output path available is `gsub(".hic","_icenorm.hic",hic_path)` when one indicates `hic_output=TRUE`. I have corrected the README files accordingly. Thank you very much!

**Comment by mervesa** [comment]
Hi, I've just pushed the changes to the vignette here and to Bioconductor's current release. The most timely way to use the changes would be to reinstall the package using devtools : library(devtools); install_github("mervesa/HiCDCPlus")
