### ISSUE TITLE
Interpretation of diagnosis plots from hicdcdiff

### ISSUE THREAD

**Issue by TingtingSsl2** [mervesa/HiCDCPlus#14]
Dear HiCDCPlus developer,

I'm wondering if you could help to understand the diagnosis plots generated from hicdcdiff function?

Thanks!

Bests,

Tingting

**Comment by mervesa** [comment]
Hi @TingtingSsl2 , as hicdcdiff largely is an implementation of DESeq2, I think the [vignette here](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) would be largely helpful as first references, so would the extensive [Q&A](https://support.bioconductor.org/u/5822/?active=posts) its creator, Michael Love, has been through. Let me know if you have a HiC specific question on any one of the plots.
