### ISSUE TITLE
other species

### ISSUE THREAD

**Issue by Nuturetree** [mervesa/HiCDCPlus#16]
Hi author
  i want to know how identify the loop expect human by HiCDCPlus.

construct_features(output_path=paste0(outdir,"/hg19_50kb_GATC"),
                   gen="Hsapiens",gen_ver="hg19",
                   sig="GATC",
                   bin_type="Bins-uniform",
                   binsize=50000,
                   chrs=c("chr21","chr22"))
how choose the "gen" and "gene_ver". example cotton

Nutures

**Comment by mervesa** [comment]
Hi @Nuturetree , we only support species with annotations on BSgenome. Could you please check this website if your species of interest exists (https://bioconductor.org/packages/release/data/annotation/)?
