### ISSUE TITLE
gi_list_topdom for all chr?

### ISSUE THREAD

**Issue by jaclyn-marie** [mervesa/HiCDCPlus#17]
Hello!

I am running HiCDC+ for hg38, and everything runs smoothly for a single chromosome. However, I am having issues getting TADs for all chromosomes.

I have tried the following:

#these both run chrs 1-3 quickly, but then gets stuck at chr4.
tads <- gi_list_topdom(gi_list, 
                       file_out = TRUE,
                       fpath = paste0(output,"/dmso"),
                       window.size = 10) 

tads <- gi_list_topdom(gi_list, 
                       file_out = TRUE,
                       chrs = NULL,
                       fpath = paste0(output,"/dmso"),
                       window.size = 10) 

#this runs for a few chromosomes, then R session gets aborted.
tads <- gi_list_topdom(gi_list, 
                        chrs = c("chr1", "chr2", "chr3", "chr4", "chr5", 
                                       "chr6", "chr7", "chr8", "chr9", "chr10",
                                       "chr11", "chr12", "chr13", "chr14", 
                                       "chr15", "chr16", "chr17", "chr18",
                                       "chr19", "chr20", "chr21", "chr22",
                                       "chrX"),
                       file_out = TRUE,
                       fpath = paste0(output,"/dmso"),
                       window.size = 10) 

#this also runs for a few chromosomes (defining tad1, tad2, tad3, etc) then R session is aborted.
tad1<- gi_list_topdom(gi_list, 
                        chrs = c("chr1"),
                       file_out = TRUE,
                       fpath = paste0(output,"/dmso"),
                       window.size = 10) 

Am I missing  something for getting this to run for all chromosomes? Any tips would be greatly appreciated!

Thanks!
Jaclyn

**Comment by mervesa** [comment]
Hi @jaclyn-marie, 

From here, it looks like you are either suffering from memory issues or Windows related File I/O issues. Unfortunately, this package does not work as reliably on Windows. You can always run results for each chromosome with a PowerShell or Bash script that runs an R script for each chromosome and combine the outputs. Let me know if that makes sense.

**Comment by jaclyn-marie** [comment]
Thank you @mervesa !
I am running HiCDC+/R through windows currently. I really appreciate the tips. I am still learning about Unbuntu/bash, but this gives me a good reason to try to get this streamlined. Thanks again for your quick reply! -J
