### ISSUE TITLE
incompatible with BSgenome.Hsapiens.NCBI.T2T.CHM13v2.0 annotation

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [mervesa/HiCDCPlus#22]
Hi, Thanks for developing this tool. I encountered an issue with `construct_features` part during testing.
```R
> construct_features(output_path=paste0(outdir,"/CHM13_50kb_GATC"),
+                    gen="Hsapiens",gen_ver="T2T.CHM13v2.0",
+                    sig="GATC",bin_type="Bins-uniform",
+                    binsize=50000,
+                    chrs=c("chr21","chr22"))
Error in library(genome, character.only = TRUE) : 
  不存在叫'BSgenome.Hsapiens.UCSC.T2T.CHM13v2.0'这个名字的程辑包
> 
```
Sorry about the default language. It means There is no package named 'BSgenome.Hsapiens.UCSC.T2T.CHM13v2.0'
The BSgenome has no `BSgenome.Hsapiens.UCSC.T2T.CHM13v2.0` but `BSgenome.Hsapiens.NCBI.T2T.CHM13v2.0` currently.
Are there any ways for me to use NCBI annotation rather than UCSC annotation during construct features?
Thanks.

**Comment by victoriafinn** [comment]
hi, 虽然我没有遇到过这个问题，但我最近也在测试这个包，遇到了一些其他的问题，也许我们可以交流一下？：D

**Comment by Gemma-Zhang-326** [comment]
> hi, 虽然我没有遇到过这个问题，但我最近也在测试这个包，遇到了一些其他的问题，也许我们可以交流一下？：D

It's my pleasure. Maybe you can email me at zhangyue1@mail.kiz.ac.cn.

**Comment by mervesa** [comment]
Hi @Gemma-Zhang-326 , the package currently runs only on genomes and versions with UCSC annotations. I will need to issue an update to use NCBI annotations. In the meantime, you can clone a copy from this repo,
change the ".UCSC" coding in the following files to ".NCBI"
`get_chrs.R`
`construct_features.R`
`get_enzyme_cutsites.R`
`get_chr_sizes.R`
and install package from source:
```
install.packages(path_to_the_cloned_and_edited_folder, repos = NULL, type="source")
```
