### ISSUE TITLE
This should work for R 4.0.3 right?

### ISSUE THREAD

**Issue by gdolsten** [mervesa/HiCDCPlus#4]
I am using R on a cluster and trying to install this program and I am getting some errors. However, this should not be related to the fact that I have R 4.0.3, correct?

**Comment by gdolsten** [comment]
In particular, I get the following error:

Installation path not writeable, unable to update packages: boot, class,
  codetools, foreign, KernSmooth, Matrix, nlme, nnet, spatial
Warning message:
package ‘HiCDCPlus’ is not available for this version of R

**Comment by mervesa** [comment]
Hi @gabedolpten , HiCDCPlus works with 4.0.3! The installation instructions in the vignette could be misleading, they'll be valid once the package gets cleared from Bioconductor, sorry about that. In the meantime, you can simply install devtools from CRAN and install from this GitHub repo:

`install.packages("devtools")` and then
`devtools::install_github("mervesa/HiCDCPlus")`
