### ISSUE TITLE
Micro-C data or DNAse Hi-C data

### ISSUE THREAD

**Issue by beoungl** [mervesa/HiCDCPlus#6]
As I was reading the Vignette, I realized that construct_features function requires restriction enzyme information; however, since Micro-C or DNase Hi-C do not use restriction enzyme, I wasn't sure whether there was an other way to find significant interactions without using construct features function.

Would just creating gi_list with empty list be enough?

**Comment by wongwic** [comment]
You should be able to run use the following settings. bin_type='Bins-uniform' and feature_type='RE-agnostic'. RE information will not be incorporated this way.

**Comment by Chaoability** [comment]
Hello,I use this set of parameters, as I find the results are not that good.So is HiCDCPlus capable for Micro-C data?The lack of RE seems critical for the model
