### ISSUE TITLE
 could not find function "add_hicpro_matrix.counts"

### ISSUE THREAD

**Issue by poflawless** [mervesa/HiCDCPlus#7]
Hello,

After I use R/4.1 version installed the software:
BiocManager::install("HiCDCPlus")
and library(HiCDCPlus)
it showed the error 
Error in add_hicpro_matrix.counts(gi_list, absfile_path, matrixfile_path,  :
  could not find function "add_hicpro_matrix.counts"

Did I miss something?

Thanks in advance

**Comment by mervesa** [comment]
Hi @poflawless , you can find the function as `add_hicpro_matrix_counts(gi_list,absfile_path,matrixfile_path,...)`; looks like there is a typo in the documentation that misled you. Thanks for identifying it! You can also view its source code [here](https://github.com/mervesa/HiCDCPlus/blob/main/R/add_hicpro_matrix_counts.R)

**Comment by poflawless** [comment]
Hello @mervesa ,

Thanks very much for your reply. whereas I have another issue:

gi_list<-generate_binned_gi_list(100000)
gi_list<-add_hicpro_matrix_counts(gi_list,"S1__abs.bed","S1_.matrix")

and in this step 
it showed that all chr does not have any counts in this file. Dropping from gi_list.

The abs and matrix file is get from hicPro output 100kb resolution and
abs file format:
Chr0    2300000 2400000 24
Chr0    2400000 2500000 25
Chr0    2500000 2600000 26
Chr0    2600000 2700000 27

matrix file like this
1       1       113
1       2       34
1       3       34
1       4       4
1       5       1
1       7       3
1       8       1
1       12      20
1       13      21

Did it due to the format or anything else?

Thanks

**Comment by poflawless** [comment]
Hello @mervesa ,
Now I checked out what's the issue; Due to the default genome is hg19 and not plant species, so it can't be matched with construct.feature step. But my confusion is that since topdom need n*(n+3)matrix from normalized data, do you have any ideas that can convert hicPro ICE matrix to n*n+3 matrix required by topdom? I checked BSgenome package, no aviable genome build version for the species I studied. Looking forward to your reply.

**Comment by mervesa** [comment]
Unfortunately, I'm sorry that this package is not planning to support genomes that doesn't have a BSgenome package. While BSgenome function [available.genomes](https://rdrr.io/bioc/BSgenome/man/available.genomes.html) lists genomes that are available on Bioconductor, but you can try to [build one yourself](https://www.bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf) or find one for your genome that is not published on Bioconductor.
